#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
# 
# This option supports custom types so lessons can be branded
# and themed with your own logo and alt-text (see `carpentry_description`)
# See https://carpentries.github.io/sandpaper-docs/editing.html#adding-a-custom-logo
carpentry: 'incubator'

# Alt-text description of the lesson.
carpentry_description: 'Learn how to run common AI/ML procedures (train, tune, etc.) using AWS SageMaker. These examples focus on narrow "predictive ML/AI" cases, where models are trained to perform a single function (contrasing with "foundation" model use via AWS Bedrock). These materials are directed towards participants of the 2024 Machine Learning Marathon, and some instructions may pertain only to that group. A more general purpose version of this workshop will be made available in future months.'

# Overall title for pages.
title: 'Intro to AWS SageMaker for Common ML/AI Procedures' # FIXME

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: 2024-10-31

# Comma-separated list of keywords for the lesson
keywords: 'AWS, SageMaker, Cloud Computing, Machine Learning, AI' # FIXME

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'pre-alpha' # FIXME

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/UW-Madison-DataScience/ml-with-aws-sagemaker'


# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'endemann@wisc.edu' 

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Order of episodes in your lesson
episodes: 
- SageMaker-overview.md
- Data-storage-setting-up-S3.md
- SageMaker-notebooks-as-controllers.md
- Accessing-S3-via-SageMaker-notebooks.md
- Interacting-with-code-repo.md
- Training-models-in-SageMaker-notebooks.md
- Training-models-in-SageMaker-notebooks-part2.md

# Information for Learners
learners: 

# Information for Instructors
instructors: 

# Learner Profiles
profiles: 

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live


